services:
  apache:
    image: php:8.1-apache
    container_name: apache
    ports:
      - 8081:80
      - 8091:8091
      - 9001:9001
      - 9002:9002
      - 9003:9003
      - 9004:9004
      - 9005:9005
      - 9006:9006
      - 9007:9007
    volumes:
      - "/var/www/form_builder:/var/www/form_builder"
      - "../apache2/configs:/etc/apache2/sites-available"
    restart: unless-stopped
